name: Segment OCR Text

on:
  workflow_dispatch:
  push:
    paths:
      - 'ocr_raw/**.txt'
      - 'preprocess/segment_text.py'

jobs:
  segment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Run segmentation script
        run: python preprocess/segment_text.py

      - name: Commit processed segments
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🧠 Segment OCR text"
          file_pattern: "processed/segments.jsonl"
